@startuml Lipho DB ER Diagram
!theme plain

entity User {
    * **username :: String**
    --
    * password :: String
    * name :: String
    * surname :: String
    email :: String
    phone :: String
    birthdate :: Date
}

entity Following {
    * **following_username :: String**
    * **followed_username :: String**
    --
    * since :: Date
}

entity Post {
    * **post_id :: Integer**
    --
    * image :: Image[1..*]
    * timestamp :: Timestamp
    * username :: String
    * average_exposure_rating :: Double
    * average_color_rating :: Double
    * average_composition_rating :: Double
    caption :: String
}

entity PostLike {
    * **post_id :: Integer**
    * **username :: String**
    --
    * timestamp :: Timestamp
}

entity Rating {
    * **post_id :: Integer**
    * **username:: String**
    --
    * post :: Post
    * exposure :: Integer[1..5]
    * colors :: Integer[1..5]
    * composition :: Integer[1..5]
}

entity Comment {
    * **post_id :: Integer**
    * **comment_id :: Integer**
    --
    * username :: String
    * post :: Post
    * timestamp :: Timestamp
    * text :: String
}

entity CommentLike {
    * **post_id :: Integer**
    * **comment_id :: Integer**
    * **username :: String**
    --
    * timestamp :: Timestamp
}

User }o--o{ Following
User }o--|| Post
Post }o--|| Rating
Post }o--|| Comment
Post }o--|| PostLike
Rating ||--o{ User
Comment ||--o{ User
Comment }o--|| CommentLike

@enduml