@startuml Lipho DB ER Diagram
!theme plain

entity user {
    * **username :: String**
    --
    * password :: String
    * name :: String
    * surname :: String
    email :: String
    phone :: String
    birthdate :: Date
}

entity following {
    * **following_username :: String**
    * **followed_username :: String**
    --
    * since :: Date
}

entity post {
    * **post_id :: Integer**
    --
    * timestamp :: Timestamp
    * username :: String
    * average_exposure_rating :: Double
    * average_color_rating :: Double
    * average_composition_rating :: Double
    caption :: String
}

entity post_image {
    * **post_id :: Integer**
    * **position :: Integer**
    --
    * image :: String
}

entity post_like {
    * **post_id :: Integer**
    * **username :: String**
    --
    * timestamp :: Timestamp
}

entity rating {
    * **post_id :: Integer**
    * **username:: String**
    --
    * exposure :: Integer[1-5]
    * colors :: Integer[1-5]
    * composition :: Integer[1-5]
}

entity comment {
    * **post_id :: Integer**
    * **comment_id :: Integer**
    --
    * username :: String
    * timestamp :: Timestamp
    * text :: String
}

entity comment_like {
    * **post_id :: Integer**
    * **comment_id :: Integer**
    * **username :: String**
    --
    * timestamp :: Timestamp
}

user }o--o{ following
user }o--|| post
post }o--|| post_image
post }o--|| rating
post }o--|| comment
post }o--|| post_like
rating ||--o{ user
comment ||--o{ user
comment }o--|| comment_like

@enduml